### ISSUE TITLE
Error in Ghost Setup

### ISSUE THREAD

**Issue by bsilvereagle** [dockerfile/ghost#25]
With a fresh docker build from dockerfiles/ghost, I get the following error when I try to setup the blog, causing the docker container to crash.

```
/ghost/core/server/mail.js:95
                if (data.error.errno === 'ENOTFOUND') {
                              ^
TypeError: Cannot read property 'errno' of null
    at EventEmitter.<anonymous> (/ghost/core/server/mail.js:95:31)
    at EventEmitter.g (events.js:180:16)
    at EventEmitter.emit (events.js:95:17)
    at DirectMailer.<anonymous> (/ghost/node_modules/nodemailer/node_modules/directmail/lib/mailer.js:138:30)
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:147:9)

npm ERR! Linux 3.18.2
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.36
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE
npm ERR! ghost@0.5.8 start: `node index`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the ghost@0.5.8 start script 'node index'.
npm ERR! This is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /ghost/npm-debug.log
```

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.3.0
3 info using node@v0.10.36
4 verbose config Skipping project config: /ghost/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT, open '/ghost/package.json'
6 verbose cwd /ghost
7 error Linux 3.18.2
8 error argv "node" "/usr/local/bin/npm" "start"
9 error node v0.10.36
10 error npm  v2.3.0
11 error path /ghost/package.json
12 error code ENOENT
13 error errno 34
14 error enoent ENOENT, open '/ghost/package.json'
14 error enoent This is most likely not a problem with npm itself
14 error enoent and is related to npm not being able to find a file.
15 verbose exit [ 34, true ]
```

Docker Version

```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8-dirty
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8-dirty
```

Node version

```
v0.10.36
```

**Comment by drewda** [comment]
This is the same problem as https://github.com/dockerfile/ghost/issues/6
